config/routes.rb
Rails.application.routes.draw do

  get 'signup'                  => 'users#new'

  # Sessions routes
  get 'login'                   => 'sessions#new'
  post 'login'                  => 'sessions#create'
  get 'logout'                  => 'sessions#destroy'
  post 'logout'                 => 'sessions#destroy'

  # OAuth routes
  get 'auth/logout'             => 'auth#logout'
  get 'auth/failure'            => 'auth#failure'
  get 'auth/:provider/callback' => 'auth#callback'

  # Password Reset routes
  get  'reset'                  => 'passwords#new'
  post 'reset'                  => 'passwords#create'
  get  'newpassword'            => 'passwords#create_new'
  post 'newpassword'            => 'passwords#update'

  # User Routes with Reviews Routes
  resources :users do
    resources :reviews
  end

  # Items Routes
  resources :items

  # Root path
  root 'main#index'

  # About Dev Team Path
  get 'main/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :item, dependent: :destroy
  has_and_belongs_to_many :reviews, dependent: :destroy

  validates :email,
        email: true,
   			presence: true,
   			uniqueness: true

  validates :first_name, :last_name,
  			presence: true

  validates :password,
  			presence: true,
        length: {
          minimum: 5,
          maximum: 20,
          too_short: " must be at least %{count} characters",
          too_long: " can have no more than %{count} characters"
        },

  			confirmation: true,
        on: :create

  has_secure_password

  def self.authenticate email, password
  	User.find_by_email(email).try(:authenticate, password)
  end

  def avg_rating person
    user_reviews = Review.select {|r| r.reviewer_id === person.id}
    puts user_reviews
  end

  def set_password_reset
    self.reset_code = SecureRandom.urlsafe_base64
    self.expires_at = 4.hours.from_now
    self.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_authenticated?, except: [:new, :create]


  def new
  end

  def create
    # Create new user if valid
    @user = User.create(user_params)

    puts @user.errors.inspect

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User Created"
      redirect_to root_path
    elsif !EmailValidator.valid?(@user.email)
       flash[:danger] = "The email you entered is invalid"
       redirect_to root_path
    else
      messages = @user.errors.map { |k, v| "#{k} #{v}" }
      flash[:danger] = messages.join(', ').gsub(/_/, ' ')
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    user = User.find params[:id]
    user.update update_user_params

    # Update image, if user uploaded an image.
    if params[:user][:image]
      uploaded_image = params[:user][:image].path
      cloud_file = Cloudinary::Uploader.upload(uploaded_image)
      if (File.exists?(uploaded_image))
        File.delete(uploaded_image)
      end
      user.update({:image => cloud_file["public_id"]})
    end

    redirect_to user
  end

  def show
    @user = User.find params[:id]
    @item = @user.item
    @reviews = Review.all.where(reviewer_id: params[:id])
    @ratingScore = []

    @reviews.each do |s|      
      @ratingScore.push(s.rating.to_f)    
    end

    @ratingTotal = @ratingScore.inject(:+)
    if @ratingTotal
      @average_rating = @ratingTotal/@ratingScore.length
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end

  private


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image, :location, :bio)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_for :user, url: 'users' do |f| %>
	<%= f.email_field :email, placeholder: "Email", hide_label: true %>
	<%= f.text_field :first_name, placeholder: "First Name", hide_label: true %>
	<%= f.text_field :last_name, placeholder: "Last Name", hide_label: true %>
	<%= f.password_field :password, placeholder: "Between 5 and 20 characters", hide_label: true %>
	<%= f.password_field :password_confirmation, placeholder: "Confirm password", hide_label: true %>
	<%= f.primary 'Sign up' %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>

<% bootstrap_form_for :user do |f| %>
	<%= f.email_field :email %>
	<%= f.text_field :first_name %>
	<%= f.text_field :last_name %>
	<%= f.password_field :password %>
	<%= f.password_field :password_confirmation %>
	<%= f.primary 'Signup' %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid userContainer">

  <section class="container-fluid" style="height:50px"></section>
  
<!--*** Begining of User info div ****-->

<div class="col-xs-12 col-sm-4 col-md-3 well userWell">
	<div class="row">
		<%= cl_image_tag(@user.image,
		                :class   => 'profileImg col-xs-4 col-sm-6 col-md-6 col-xs-offset-4 col-sm-offset-3 col-md-offset-3',
		                :crop    => :fill,
		                :gravity => :face) %>
    </div>
    <hr>
	<div class="about">
		<h1><%= @user.first_name %> <%= @user.last_name.first %>.<br><small>Member Since <%= @user.created_at.strftime("%m/%Y") %><br>From</small> <small style="color:rgb(54,128,55)"><%=@user.location %></small></h1>
	</div>
	<hr>
      <div class="bio"><h2><%= @user.bio %></h2></div>
    <hr>
    <div class="rating hidden-xs">
                  <% if @ratingTotal != nil %>
                  <h2><% @average_rating.floor.times do |i| %>
                  <i class="fa fa-star"></i>
                  <% end %>
                  <% decimal = (@average_rating - (@average_rating.floor)) %>
                  <% if decimal >= 0.3 %>
                    <% if decimal < 0.8 %>
                      <i class="fa fa-star-half-o"></i>
                    <% else %>
                      <i class="fa fa-star"></i>
                    <% end %>
                    <% (5 - (@average_rating.floor + 1)).times do |i| %>
                    <i class="fa fa-star-o"></i>
                    <% end %>
                  <% else %>
                    <% (5 - @average_rating.floor).times do |i| %>
                    <i class="fa fa-star-o"></i>
                    <% end %>
                  <% end %>
                  </h2>
                  <!-- <h2>Average Rating: <%= @average_rating.round(1) %></h2> -->
                  <h2>Number of Reviews: <%= @ratingScore.length %></h2>
                  <% else %>
                  <h2>No ratings for this user yet</h2>
                  <% end %>
    </div>
    <hr>
<!-- ***** profile buttons ***** -->    
    <div class="col-xs-12 col-sm-12 col-md-12">
      <% if @current_user.id === @user.id %>
      		<button type="button" class="btn nav-btn updateModalBtn col-xs-5 col-sm-5 col-md-5" data-toggle="modal" data-target="#profileModal">Edit Info</button>
      			<div class="col-xs-2 col-sm-2 col-md-2"></div>
      		<span><%= link_to "List Item", new_item_path, class: "btn nav-btn modalBtn col-xs-5 col-sm-5 col-md-5" %></span>
      <% end %>
    </div>
<!-- ***** Prolile edit Modal ***** -->
<div class="modal fade" id="profileModal" tableindex="-1" role="dialog" aria-labelledby="profileModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
              <h4 class="modal-title" id="profileModalLabel"><strong>Edit User Information</strong></h4>
            </div>
            <div class="modal-body">

              <%= bootstrap_form_for @user, url: { :action => "update", :controller => "users"}, :method => "put" do |u| %>
                <%= u.text_field :first_name, hide_label: true %>
                <%= u.text_field :last_name, hide_label: true %>
                <%= u.text_field :email, hide_label: true %>
                <%= u.select :location,
                  [
                    ["Seattle"], ["Bellevue"], ["Green Lake"], ["Bothell"], ["West Seattle"], ["Northgate"], ["Ballard"]

                ], { label: "Choose your neighborhood" }, { class: "selectpicker" }
                  %>
                <%= u.text_area :bio, placeholder: "Write a bio", hide_label: true %>
                <%= u.file_field :image, label: "Input an image", :class => "col-md-6 col-md-offset-3 imageInput" %>
                <%= u.primary "Update" %>
              <% end %>
              <%= link_to "Delete", @user, :class => 'btn btn-danger userDelete', :data => {:confirm => 'Are you sure?'}, :method => :delete %>
            </div>
          </div>
        </div>
      </div>
    </div>
<div class="col-sm-1 col-md-1 hidden-xs"></div>
<!--**** Beginning of item container ****-->
	<% if @item.length > 0 %>
	<div class="col-xs-12 col-sm-7 col-md-8 itemsDiv"> 
		<div class="col-xs-12 col-sm-12 col-md-12 innerItemDiv">
		<h2 style="text-align:center"><%= @user.first_name %>'s Items for rent: </h2><hr>

<!--**** Beginning of item and review container ****-->
<!--   <div class="container">
    <div class="col-xs-12 col-sm-9 col-md-9 userItems">
 -->
        <% @item.each do |i| %>
          <div class="col-xs-6 col-sm-6 col-md-4">
            <%= cl_image_tag(i.image,
                          :height  => 250,
                          :width   => 200,
                          :crop    => :fill,
                          :gravity => :face,
                          :class   => "cloudImg"
                      )
            %>
            <div class="itemDescripDiv">
              <h2><%= i.title %></h2>
                <% if i.rented == false %>
                                <a href="mailto:<%= @user.email %>?subject=Rent <%= i.title %>", class: "btn btn-success btn-sm modalBtn">Contact About Renting</a> <br>
                              <% else %>
                                <p>Not Currently Available</p>
                              <% end %>
                  <hr><br>
              <p>$<%= i.price_day %>/day | $<%= i.price_week %>/week <br> <%= i.description %></p> 
              <% if @current_user.id === @user.id %>
                <%= link_to "Edit Item", item_path(i) %>
              <% end %>

            </div>
          </div>
    <% end %>
    </div>
</div>
<% end %>

<!--******** Begining of reviews container ********-->

<div class="col-xs-12 col-sm-7 col-md-8 reviewDiv">
	<div class="well wellWell container"><h1>Reviews about <%= @user.first_name %></h1>
        <% if @current_user.id != @user.id %>
          <button type="button" class="btn nav-btn modalBtn" data-toggle="modal" data-target="#reviewModal">Review <%= @user.first_name %></button>
          <% else %>
          <button type="button" class="btn nav-btn modalBtn disabled" data-toggle="modal" data-target="#reviewModal">Review <%= @user.first_name %></button>
        <% end %>
    </div>
<!--********** Review Modal ***********-->
    <div class="modal fade" id="reviewModal" tableindex="-1" rolde="dialog" aria-labelledby="reviewModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
              <h4 class="modal-title" id="reviewModalLabel">Review for <%= @user.first_name %> <%= @user.last_name.first %>.</h4>
            </div>
            <div class="modal-body">
              <%= render 'reviews/form' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-warning close" data-dismiss="modal" aria-label="Close">Close</button>
            </div>
          </div>
        </div>
      </div>

<!--************** Reviews Show section *************-->
	<div class="well reviewWell">
	   <% if @reviews.distinct.count('review') === 0 %>
	        <h4>This user doesn't have any reviews yet. You could be the first!</h4>
	   <% else %>
	        <% @reviews.each do |r| %>
	          	<% if r.reviewer_id === @user.id %>
	          		<h2><%= r.review %></h2>
	          		<h3> Rating of : <%= r.rating %>/5           
	            <% if r.first_name %>
	              	<small>Written by : <%= r.first_name %>
	            <% end %>           
	            <% if r.last_name %>
	              	<%= r.last_name.first %>.
	            <% end %> on : <%= r.created_at.strftime("%m/%d/%Y") %></small></h3>
	            <hr>    
	         	<% end %>
	        <% end %>
	    <% end %>
	</div>
<!-- 
      <div class="well reviewWell">
      <% if @reviews.distinct.count('review') === 0 %>
            <h4>This user doesn't have any reviews yet. You could be the first!</h4>
            <% else %>

        <% @reviews.each do |r| %>

          <% if r.reviewer_id === @user.id %>


          <h2><%= r.review %></h2>
          <h3> Rating of : <%= r.rating %>/5

            <% if r.first_name %>
              <small>Written by : <%= r.first_name %>
            <% end %>

            <% if r.last_name %>
              <%= r.last_name.first %>.
            <% end %> on : <%= r.created_at.strftime("%m/%d/%Y") %></small></h3>
            <hr>


          <% end %>

        <% end %>
        <% end %>
      </div>
    </div> -->
  </div>


</div>
	

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>