config/routes.rb
Rails.application.routes.draw do

  get 'signup'                  => 'users#new'

  # Sessions routes
  get 'login'                   => 'sessions#new'
  post 'login'                  => 'sessions#create'
  get 'logout'                  => 'sessions#destroy'
  post 'logout'                 => 'sessions#destroy'

  # OAuth routes
  get 'auth/logout'             => 'auth#logout'
  get 'auth/failure'            => 'auth#failure'
  get 'auth/:provider/callback' => 'auth#callback'

  # Password Reset routes
  get  'reset'                  => 'passwords#new'
  post 'reset'                  => 'passwords#create'
  get  'newpassword'            => 'passwords#create_new'
  post 'newpassword'            => 'passwords#update'

  # User Routes with Reviews Routes
  resources :users do
    resources :reviews
  end

  # Items Routes
  resources :items

  # Root path
  root 'main#index'

  # About Dev Team Path
  get 'main/about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,200,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Russo+One|Fredoka+One|Lobster+Two:700italic|Black+Ops+One' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <title>RentRabbit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="col-md-2 col-md-offset-5">
  <a class="navbar-brand brand hidden-xs hidden-sm" href="/">
  <img alt="Brand" class="logoImg" src="<%= asset_path('Rent-Rabbit-Logo-words.svg') %>">
  </a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right col-sm-6 col-md-5">
       <li class="col-md-4 hidden-sm"><a href="/items">For rent</a></li>
        <%= form_tag(items_path, :method => 'get', id: "search-form", :class => "navbar-form navbar-right col-sm-12 col-md-8 hidden-xs") do  %>
       <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Items", :class => "form-control" %>
        </div>
        <%= submit_tag 'Submit', :class => "btn btn-success nav-btn" %>
        <% end %>
   </ul>
    <ul class="nav navbar-nav navbar-left col-sm-6 col-md-5">
    <% if @current_user %>
 <li class="col-sm-6 col-md-6"><%= link_to @current_user.first_name + "'s profile", "/users/" + @current_user.id.to_s %></li> <li class="col-sm-6 col-md-6"><%= link_to "Logout", logout_path %></li>
      <% else %>
      <li class="col-sm-6 col-md-6"><a data-toggle="modal" href="#login">Log in</a></li>
      <li class="col-sm-6 col-md-6"><a data-toggle="modal" href="#signup">Sign Up</a></li>
    <% end %>
    </ul>
  </div>
  </div>
  <%= render 'partials/flash' %>
</nav>



<%= yield %>

<!-- Login Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="login">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Login</h4>
			</div>
			<div class="modal-body">
				<%= render 'sessions/form' %>
			</div>
		</div>
	</div>
</div>

<!-- Signup Modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="signup">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Sign Up</h4>
			</div>
			<div class="modal-body">
				<%= render 'users/form' %>
			</div>
		</div>
	</div>
</div>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
<%= javascript_include_tag '_main.js' %>
<%= javascript_include_tag 'skrollr.js' %>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</body>

</html>